name: Test
run-name: ${{ github.actor }} is testing


on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - CHANGELOG.md # Should never be edited anyway
      - .gitignore
      - .github/**
  pull_request_target:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:


jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Run in all these versions of Python
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-datafiles
        python -m pip install -e .
    - name: Test with pytest
      run: 
        python -m pytest tests

  mypy:
    name: Type check code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy
    - name: Type check code
      run: |
        python -m mypy src
    - name: Type check tests
      run: |
        python -m mypy tests
